[DPN-24/Localstorage] add icon for export data to json/copy current l…
solenoid-pdx/solenoid pull request #20
Opened 2021-02-08 07:12 UTC by Yifan-Zhang618

…ink and an input file area for uploading .json file

add 2 icons and 1 file input section
icon#1: click for exporting data as a JSON file, on hover for its description
icon#2: click for copying the current link, on hover for its description
file input section: upload JSON file as input data

2021-02-08 23:22 UTC, trevorliberty requested changes
Only minor changes needed.
Make sure you write unit tests for these changes as well

2021-02-08 23:22 UTC, trevorliberty commented on static/js/localStorage.js
> +    let filename = "input.json";
Let's rename this to "parameters.json"

2021-02-09 02:11 UTC, Yifan-Zhang618 commented
I Will add a unit test  later when I figure it out

2021-02-11 19:40 UTC, jjesse55 commented
Make sure to pull in the latest changes from master as their was a PR that got merged last night

2021-02-11 20:52 UTC, trevorliberty reviewed
Let's add a test for downloading and copying the link successfully as well

2021-02-12 03:17 UTC, closed without merging