[DPN-24/LocalStorage] update to master, so far 1 test for each functi…
solenoid-pdx/solenoid pull request #25
Opened 2021-02-12 03:57 UTC by Yifan-Zhang618

…on, will add test later and refactor format later

2021-02-12 10:33 UTC, trevorliberty commented
That failing check is actually an interesting problem. We may need to approach that copy link feature another way. There is no copying mechanism on a headless version of chrome:

https://stackoverflow.com/questions/53080757/python-3-selenium-clipboard-not-working-on-headless-chromedriver-on-windows

https://stackoverflow.com/questions/59409183/python-selenium-clipboard-functionality-ctrl-c-not-working-in-firefox-headl

Apparently we can use a workaround with phantomjs, but this seems like an awful lot of overhead. We may want to ignore this in the effort of getting this PR through

2021-02-13 02:36 UTC, jjesse55 commented
@trevorliberty @Yifan-Zhang618 In the sake of time, I agree. However instead of ignoring the failures I would say comment out test(s) for now, create a new issue for finding the fix to this, and assign it to Yifan since he's already tried a few things.

2021-02-13 02:51 UTC, jjesse55 requested changes

2021-02-13 02:51 UTC, jjesse55 commented on selenium_tests/test_storage.py
> +        self.driver.quit()
- Inherit from the SeleniumTestBase
- remove last three lines of constructor
- remove setup, teardown methods

2021-02-13 02:51 UTC, jjesse55 commented on selenium_tests/test_storage.py
> +        time.sleep(2)
Just curious, does it not copy in time without a call to sleep?

2021-02-13 02:51 UTC, jjesse55 commented on requirements.txt
> +pyperclip==1.8.1
Are you still using this dependency or was this left over from debugging the copy/paste testing issue?

2021-02-13 02:52 UTC, jjesse55 commented on requirements.txt
> +pyperclip==1.8.1
Pyperclip, that is

2021-02-14 20:19 UTC, jjesse55 approved these changes

2021-02-14 20:21 UTC, jjesse55 commented on requirements.txt
> +pyperclip==1.8.1
@Yifan-Zhang618 is this dependency still needed?

2021-02-17 03:21 UTC, trevorliberty approved these changes

2021-02-17 07:21 UTC, merged